version: "3"

services: 
  old-slovaks-express:
    build: .
    ports: 
      - "3000:3000"
    networks: 
      - old-slovaks
    depends_on: 
      - postgres
  postgres:
    image: postgres
    environment: 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes: 
      - "pgdata:/var/lib/postgresql/data"
    networks: 
      - old-slovaks

networks: 
  old-slovaks:

volumes: 
  pgdata: