version: "3"
services:
  api:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on: 
      - postgres
    volumes: 
      - "./src:/app/src"

  postgres:
    image: postgres
    restart: unless-stopped
    environment: 
      POSTGRES_USER: ${OLD_SLOVAK_USERNAME}
      POSTGRES_PASSWORD: ${OLD_SLOVAK_PASSWORD}
      POSTGRES_DB: ${OLD_SLOVAK_DATABASE}
    ports: 
      - "5432:5432"
    volumes: 
      - "pg-old-slovaks-dev:/var/lib/postgresql/data"

volumes:
  pg-old-slovaks-dev: